
export interface AppState {
  steps: number,
  selectedDate: string,
  selectedAppointmentType: string,
  selectedAppointmentName: string,
  selectedTime: string,
  name: string,
  lastName: string,
  birthday: string,
  telNr: string,
  emailAddress: string,
  patNr: string,
  notice: string,
  stepOneValid: boolean,
  stepTwoValid: boolean,
  stepThreeValid: boolean,
  stepFourValid: boolean,
  stepFiveValid: boolean,
  appointmentTypeNr: string,
  raumNr: string,
  responseDates: unknown[],
  timeSlots: unknown[],
  timeSlotsLoading: boolean,
}

export function createAppState(): AppState {
  return {
    steps: 0,
    selectedDate: '',
    selectedAppointmentType: '',
    selectedAppointmentName: '',
    selectedTime: '',
    name: '',
    lastName: '',
    birthday: '',
    telNr: '',
    emailAddress: '',
    notice: '',
    patNr: '',
    stepOneValid: false,
    stepTwoValid: false,
    stepThreeValid: false,
    stepFourValid: false,
    stepFiveValid: false,
    appointmentTypeNr: '',
    raumNr: '',
    responseDates: [],
    timeSlots: [],
    timeSlotsLoading: true
  };
}
