/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appointment: typeof import('./components/step2/Appointment.vue')['default']
    AppointmentType: typeof import('./components/step2/AppointmentType.vue')['default']
    Calendar: typeof import('./components/step3/Calendar.vue')['default']
    Final: typeof import('./components/step5/Final.vue')['default']
    FinalForm: typeof import('./components/step5/FinalForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stammpatient: typeof import('./components/step1/Stammpatient.vue')['default']
    TimeSlots: typeof import('./components/step4/TimeSlots.vue')['default']
  }
}
